@startuml
package util {
  class SudokuCache
  note left: Singleton & Dependency Injection
}

package model {
  class Game
  Game -d-> Puzzle
  Game -> State
  Game -u-> SudokuCache

  abstract class PuzzleFactory
  note left: Abstract Factory
  PuzzleFactory -> SquareVisitor

  PuzzleFactory -u[hidden]-> SixSqPuzzle

  class FourSqFactory extends PuzzleFactory
  class SixSqFactory extends PuzzleFactory
  class NineSqFactory extends PuzzleFactory
  class JigsawFactory extends PuzzleFactory
  class SamuraiFactory extends PuzzleFactory

  abstract class Puzzle
  interface Square
  Puzzle -l-* Square

  class DefaultSquare extends Square

  interface SquareVisitor
  class PuzzleSquareVisitor extends SquareVisitor
  note right of SquareVisitor: Visitor

  class FourSqPuzzle extends Puzzle
  class SixSqPuzzle extends Puzzle
  class NineSqPuzzle extends Puzzle
  class JigsawPuzzle extends Puzzle
  class SamuraiPuzzle extends Puzzle

  abstract class State
  note right: State

  class PlayState extends State
  class NoteState extends State

  abstract class Command
  Command -> Game
  note left of Command: Command

  class EnterCommand extends Command
  class StartCommand extends Command
}

package controller {
  abstract class Controller {
    #sudoku: Sudoku
    {abstract} +createView(): View
  }

  class OverviewController extends Controller
  class PuzzleController extends Controller
}

package widget {
  abstract class Widget {
    {abstract} +draw(Graphics2D)
    {abstract} +update()
  }
  class WidgetGroup extends Widget {
    #children: Widget[]
    +draw(Graphics2D)
    +update()
    +getChildren(): List<Widget>
    +findChild(): Widget
  }
  WidgetGroup *-u- Widget
  note left of Widget: Composite

  class ButtonWidget extends Widget {
    +draw(Graphics2D)
    +update()
  }

  class FrameWidgetGroup extends WidgetGroup {
    +draw(Graphics2D)
    +update()
  }
}

package view {
  abstract class View extends WidgetGroup

  class OverviewView extends View {
    +draw(Graphics2D)
    +update()
  }
  OverviewView -> OverviewController
  class PuzzleView extends View {
    +draw(Graphics2D)
    +update()
  }
  PuzzleView -> PuzzleController
}

class Sudoku {
  -controller: Controller
  +openController(Class<Controller>)
}
note right: MVC & Factory Method

Sudoku <-u-> Controller
Controller -u-> View
Sudoku -d-> Game
Sudoku -u-> Widget
@enduml
